### ISSUE TITLE
Most asserted traits of "Order Topology" are incorrect

### ISSUE THREAD

**Issue by aPhyscher** [jamesdabbs/pi-base.hs#55]
I don't know where it's appropriate to report this (I have tried email, but no response over a period of a few months), but the (online) asserted traits for the Order Topology are mostly incorrect. Of course these inaccuracies then spill over into the deduced traits.

* Cardinality ≤2^(c): Depends on the particular space
* Second Category: Depends on the particular space
* Scattered: Depends on the particular space
* ¬Extremally Disconnected: Depends on the particular space
* ¬First Countable: Depends on the particular space
* ¬Locally Compact: Depends on the particular space
* ¬Pseudocompact: Depends on the particular space
* ¬Countable Chain Condition: Depends on the particular space
* ¬Countably Paracompact: False (all ordered spaces are countably paracompact)
* Metacompact: Depends on the particular space
* ¬Normal: False (all ordered spaces are normal)
* Zero Dimensional: Depends on the particular space
* T_3(1/2): True
* ¬Weakly Countably Compact: Depends on the particular space
* T_2(1/2): True

In general, there should be a better way to report inaccuracies in the data.

**Comment by jamesdabbs** [comment]
Replied via email, but in case anyone else ends up here:

* Thanks for the reports, I'll correct them soon :+1:
* Site admins do have access to editing tools; if anyone is interested in becoming a moderator, get in touch with me.

Thanks for the report :+1:
